### ISSUE TITLE
Turn off 'applyPersistentStyles' style injection

### ISSUE THREAD

**Issue by bluetidepro** [mobify/pikabu#34]
What is the point of having `this.applyPersistentStyles();` (https://github.com/mobify/pikabu/blob/master/src/pikabu.js#L271) in the JS when those same things are also already in the CSS? I don't get why those are in both? It just makes it difficult to override things when it appears in the `<head>`. Or if anything, could their be an option made to turn off `applyPersistentStyles`?

**Comment by highruned** [comment]
Hi @bluetidepro - Thanks for the report!

We've added an option to turn it off, in the `pikabu-1.0` branch.

``` js
$('m-pikabu').pikabu({
    useDefaultAnimation: false
});
```

Please re-open if you still have issues. Cheers and thanks again!
