### ISSUE TITLE
Pikabu 2.0: how to mark up the body content

### ISSUE THREAD

**Issue by vmarta** [mobify/pikabu#51]
The readme for Pikabu 2.0 needs to indicate what the minimum expected markup that works. 

Currently, the readme essentially asks you to do this:

```
<div id="yourPikabu" hidden>
    Your pikabu content
</div>
<script>$('#yourPikabu').pikabu()</script>
```

But that's not enough.. it doesn't say how to mark up the _body_ content too. I had to add the following markup in current project:

```
<div class="pikabu">
    <div class="pikabu__container">
        // header, main, footer would go here
    </div>
</div>

```

What is supposed to be the markup for it? Thanks.

**Comment by donnielrt** [comment]
@vmarta do you know if we're using Pikabu 2.0 in any projects?

**Comment by vmarta** [comment]
@donnielrt sorry for the delay. JTV uses pikabu 2: https://github.com/mobify/jtv-mobile/blob/master/bower.json#L20
