### ISSUE TITLE
Pikabu 2.0: Perspective effect doesn't have a proper close hit target

### ISSUE THREAD

**Issue by stewartyu** [mobify/pikabu#64]
As per the screenshot, only the translucent area can be tapped to close the menu. 

Expected: You can tap anywhere outside the menu to close it.

<img width="398" alt="screen shot 2016-01-07 at 6 55 47 pm" src="https://cloud.githubusercontent.com/assets/982115/12189175/5637458e-b570-11e5-9208-a27813b181e5.png">

**Comment by stewartyu** [comment]
Instead of fixing this, we're dropping support for this effect as it's not something we actively use on any of our customers' sites.

**Comment by kpeatt** [comment]
Aw but it's SOO COOOL.

**Comment by stewartyu** [comment]
If you want to PR a fix, be my guest!

**Comment by kpeatt** [comment]
![be-our-guest-lumiere-o](https://cloud.githubusercontent.com/assets/447683/12524533/92d2c4f2-c12b-11e5-892d-d3ba574afc83.gif)

**Comment by scalvert** [comment]
Is that a 'no'?
