### ISSUE TITLE
Sliding animation is not consistent

### ISSUE THREAD

**Issue by ericmuyser** [mobify/pikabu#9]
http://mobify.github.io/pikabu/

It's easy to see. 
Open: you cant see Left coming in from the side, as it's already there. 
Close: you see Left going away to the side.

The Right side is consistent though. I imagine it is due to some sort of width tweening, doing it from the right side, so it's only noticeable on Left while opening? Not sure.

**Comment by highruned** [comment]
I'm quite sure this is fixed :)
